version: 2
project_name: startAutoscale

before:
  hooks:
    - go mod tidy

builds:
  - id: app
    binary: startAutoscale
    main: .
    env:
      - CGO_ENABLED=0

archives:
  - formats: [tar.gz]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
